# Generated by Django 6.0.2 on 2026-03-07 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='Doğru Sayısı')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Toplam Soru')),
                ('percentage', models.PositiveIntegerField(default=0, verbose_name='Yüzde Skor')),
                ('passed', models.BooleanField(default=False, verbose_name='Geçti')),
                ('elapsed_seconds', models.PositiveIntegerField(default=0, verbose_name='Geçen Süre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tamamlanma Tarihi')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Quiz Denemesi',
                'verbose_name_plural': 'Quiz Denemeleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField(default=0, verbose_name='Soru Sırası')),
                ('question_text', models.TextField(verbose_name='Soru Metni')),
                ('selected_answer_index', models.IntegerField(blank=True, null=True, verbose_name='Seçilen Cevap İndeksi')),
                ('selected_answer_text', models.CharField(blank=True, max_length=255, verbose_name='Seçilen Cevap')),
                ('correct_answer_index', models.PositiveIntegerField(verbose_name='Doğru Cevap İndeksi')),
                ('correct_answer_text', models.CharField(max_length=255, verbose_name='Doğru Cevap')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Doğru mu')),
                ('image', models.URLField(blank=True, verbose_name='Görsel URL')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Görsel Alt')),
                ('image_caption', models.CharField(blank=True, max_length=255, verbose_name='Görsel Açıklama')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizattempt', verbose_name='Deneme')),
            ],
            options={
                'verbose_name': 'Deneme Cevabı',
                'verbose_name_plural': 'Deneme Cevapları',
                'ordering': ['question_order', 'id'],
            },
        ),
    ]
