# Generated by Django 6.0.2 on 2026-03-07 20:31

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_question_options(apps, schema_editor):
    QuizQuestion = apps.get_model('quiz', 'QuizQuestion')
    QuizAnswerOption = apps.get_model('quiz', 'QuizAnswerOption')

    for question in QuizQuestion.objects.all().iterator():
        legacy_options = question.options if isinstance(question.options, list) else []
        has_question_image = isinstance(question.image, str) and bool(question.image.strip())

        question.question_type = (
            'image_question_text_answers' if has_question_image else 'text_question_text_answers'
        )
        question.save(update_fields=['question_type'])

        if QuizAnswerOption.objects.filter(question=question).exists():
            continue

        for option_index, option_text in enumerate(legacy_options):
            QuizAnswerOption.objects.create(
                question=question,
                text=option_text,
                image='',
                image_alt='',
                is_correct=(option_index == question.correct_answer),
                display_order=option_index,
                is_active=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattemptanswer',
            name='correct_answer_image',
            field=models.URLField(blank=True, verbose_name='Doğru Cevap Görseli'),
        ),
        migrations.AddField(
            model_name='quizattemptanswer',
            name='correct_answer_image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Doğru Cevap Görsel Alt'),
        ),
        migrations.AddField(
            model_name='quizattemptanswer',
            name='selected_answer_image',
            field=models.URLField(blank=True, verbose_name='Seçilen Cevap Görseli'),
        ),
        migrations.AddField(
            model_name='quizattemptanswer',
            name='selected_answer_image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Seçilen Cevap Görsel Alt'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('text_question_text_answers', 'Metin soru + metin cevaplar'), ('image_question_text_answers', 'Resimli soru + metin cevaplar'), ('text_question_image_answers', 'Metin soru + resimli cevaplar'), ('image_question_image_answers', 'Resimli soru + resimli cevaplar')], default='text_question_text_answers', max_length=40, verbose_name='Soru Tipi'),
        ),
        migrations.CreateModel(
            name='QuizAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='Cevap Metni')),
                ('image', models.URLField(blank=True, verbose_name='Cevap Görseli')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Cevap Görsel Alt Metni')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Doğru Cevap')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='quiz.quizquestion', verbose_name='Soru')),
            ],
            options={
                'verbose_name': 'Cevap Şıkkı',
                'verbose_name_plural': 'Cevap Şıkları',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.RunPython(migrate_legacy_question_options, migrations.RunPython.noop),
    ]
