# Generated by Django 6.0.2 on 2026-03-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizattemptanswer_correct_answer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizansweroption',
            name='image_file',
            field=models.FileField(blank=True, upload_to='quiz/answers/', verbose_name='Cevap Görsel Dosyası'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image_file',
            field=models.FileField(blank=True, upload_to='quiz/questions/', verbose_name='Görsel Dosyası'),
        ),
    ]
