# Generated by Django 6.0.2 on 2026-03-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizansweroption_image_file_quizquestion_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='thumbnail_file',
            field=models.FileField(blank=True, upload_to='quiz/thumbnails/', verbose_name='Kapak Görsel Dosyası'),
        ),
    ]
