# Generated by Django 6.0.2 on 2026-03-02 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=100, verbose_name='Quiz ID')),
                ('quiz_title', models.CharField(max_length=255, verbose_name='Quiz Adı')),
                ('player_one_name', models.CharField(max_length=50, verbose_name='Oyuncu 1')),
                ('player_two_name', models.CharField(max_length=50, verbose_name='Oyuncu 2')),
                ('player_one_score', models.PositiveIntegerField(default=0, verbose_name='Oyuncu 1 Skoru')),
                ('player_two_score', models.PositiveIntegerField(default=0, verbose_name='Oyuncu 2 Skoru')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Toplam Soru')),
                ('winner', models.CharField(blank=True, max_length=50, verbose_name='Kazanan')),
                ('status', models.CharField(choices=[('completed', 'Tamamlandı'), ('time_up', 'Süre Doldu')], default='completed', max_length=20, verbose_name='Durum')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='Oynanma Tarihi')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multiplayer_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Ev Sahibi')),
            ],
            options={
                'verbose_name': 'Çok Oyunculu Maç',
                'verbose_name_plural': 'Çok Oyunculu Maçlar',
                'ordering': ['-played_at'],
            },
        ),
    ]
