# Generated by Django 6.0.2 on 2026-03-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('show_on_homepage', models.BooleanField(default=True, verbose_name='Ana Sayfada Göster')),
            ],
            options={
                'verbose_name': 'SSS Maddesi',
                'verbose_name_plural': 'SSS Maddeleri',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Ana Sayfa Özelliği',
                'verbose_name_plural': 'Ana Sayfa Özellikleri',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='ph ph-chart-bar', max_length=80, verbose_name='İkon Sınıfı')),
                ('value', models.CharField(max_length=80, verbose_name='Değer')),
                ('label', models.CharField(max_length=120, verbose_name='Etiket')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Ana Sayfa İstatistiği',
                'verbose_name_plural': 'Ana Sayfa İstatistikleri',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='QuizFlow', max_length=120, verbose_name='Site Adı')),
                ('footer_meta', models.CharField(default='QuizFlow (c) 2026', max_length=255, verbose_name='Footer Meta')),
                ('footer_copy', models.CharField(default='Bilgini güçlendiren modern quiz deneyimi.', max_length=255, verbose_name='Varsayılan Footer Metni')),
                ('hero_title', models.CharField(default='Bilgini sadece ölçme, hikâyeye dönüştür', max_length=255, verbose_name='Ana Sayfa Başlığı')),
                ('hero_description', models.TextField(blank=True, verbose_name='Ana Sayfa Açıklaması')),
                ('faq_page_title', models.CharField(default='Sıkça Sorulan Sorular', max_length=255, verbose_name='SSS Başlığı')),
                ('faq_page_description', models.TextField(blank=True, verbose_name='SSS Açıklaması')),
                ('terms_page_title', models.CharField(default='Kullanım Şartları', max_length=255, verbose_name='Şartlar Başlığı')),
                ('terms_page_description', models.TextField(blank=True, verbose_name='Şartlar Açıklaması')),
                ('terms_note_prefix', models.CharField(blank=True, max_length=255, verbose_name='Şartlar Not Ön Ek')),
                ('terms_note_link_label', models.CharField(blank=True, max_length=120, verbose_name='Şartlar Not Link Yazısı')),
                ('terms_note_link_url', models.CharField(blank=True, max_length=255, verbose_name='Şartlar Not Link URL')),
                ('terms_note_suffix', models.CharField(blank=True, max_length=255, verbose_name='Şartlar Not Son Ek')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Ad')),
                ('url', models.URLField(verbose_name='URL')),
                ('icon_class', models.CharField(default='ph ph-link', max_length=80, verbose_name='İkon Sınıfı')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Sosyal Medya Linki',
                'verbose_name_plural': 'Sosyal Medya Linkleri',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TermsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('show_on_homepage', models.BooleanField(default=True, verbose_name='Ana Sayfada Göster')),
            ],
            options={
                'verbose_name': 'Şart Maddesi',
                'verbose_name_plural': 'Şart Maddeleri',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
