# Generated by Django 6.0.2 on 2026-03-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homefeature',
            name='image',
            field=models.URLField(blank=True, verbose_name='Görsel URL'),
        ),
        migrations.AddField(
            model_name='homefeature',
            name='image_file',
            field=models.FileField(blank=True, upload_to='content/features/', verbose_name='Görsel Dosyası'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.URLField(blank=True, verbose_name='Hero Görsel URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_file',
            field=models.FileField(blank=True, upload_to='content/hero/', verbose_name='Hero Görsel Dosyası'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.URLField(blank=True, verbose_name='Site Logo URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo_file',
            field=models.FileField(blank=True, upload_to='content/site/', verbose_name='Site Logo Dosyası'),
        ),
    ]
